#!/bin/bash
#Date 2020/3/18
[ $(id -u) != "0" ] && echo "Error: You must be root to run this script" && exit 1
#export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
ip=`ip address |grep inet |grep -v inet6 |grep -v 127.0.0.1 |awk '{print $2}'| awk -F "/" '{print $1}'|sed -n "1p"`
echo "本机ip为:$ip"

echo "关闭防火墙"
sed -i "s/SELINUX=enforcing/SELINUX=disabled/"  /etc/selinux/config
setenforce 0
systemctl stop firewalld
systemctl disable firewalld

echo "同步服务器时间"
which  ntpd
if [ $? -ne 0 ];then
	 yum install ntpdate -y
    /usr/sbin/ntpdate time1.aliyun.com
    echo "*/5 * * * * /usr/sbin/ntpdate -s time1.aliyun.com">>/var/spool/cron/root    
else
    /usr/sbin/ntpdate time1.aliyun.com
    echo "*/5 * * * * /usr/sbin/ntpdate -s time1.aliyun.com">>/var/spool/cron/root
fi

echo "创建zabbix用户和组"
user=zabbix
group=zabbix

grep "^$group" /etc/group > /dev/null 2>&1
if      [ $? -eq 0 ];then
        echo "已创建zabbix Gruop"
else
        groupadd zabbix -g 201
fi

grep "^$user" /etc/passwd  > /dev/nulil 2>&1
if      [ $? -eq 0 ];then
        echo "已存在zabbix User"
else
        useradd -g zabbix -u 201 -m -s /sbin/nologin zabbix
fi

sleep 3
echo "数据库密码"
while :
do
read -p  "请输入mariadb root passwod: " passwod
        [ -n $passwod ] && break
done
	

sleep 5

#安装zabbix
echo "##########################################"
echo "#       Auto Install zabbix.            ##"
echo "#       Press Ctrl + C to cancel        ##"
echo "#       Any key to continue             ##"
echo "##########################################"
echo "(1) Install zabbix4.0"
echo "(2) Install zabbix4.2"
echo "(3) Install zabbix4.4"
echo "(4) EXIT"
read -p "Please input your choice:" NUM
case $NUM in 
1)
	
	echo "安装zabbix4.0源"
	echo "使用阿里源"	
	rpm -i https://mirrors.aliyun.com/zabbix/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
	sed -i 's@repo.zabbix.com@mirrors.aliyun.com/zabbix@g' /etc/yum.repos.d/zabbix.repo
	yum clean all
	yum makecache
;;
2)
    echo "正在安装zabbix.4.2"
	rpm -i https://mirrors.aliyun.com/zabbix/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-1.el7.noarch.rpm
	sed -i 's@repo.zabbix.com@mirrors.aliyun.com/zabbix@g' /etc/yum.repos.d/zabbix.repo
	yum clean all
	yum makecache
;;
3)
	echo "正在安装zabbix.4.4"
	rpm -i https://mirrors.aliyun.com/zabbix/zabbix/4.4/rhel/7/x86_64/zabbix-release-4.4-1.el7.noarch.rpm
	sed -i 's@repo.zabbix.com@mirrors.aliyun.com/zabbix@g' /etc/yum.repos.d/zabbix.repo
	yum clean all
	yum makecache
;;
4)
    echo -e "\033[41;37m You choice channel! \033[0m" && exit 0
;;
*)
    echo -e "\033[41;37m Input Error! Place input{1|2|3|4} \033[0m" && exit 1
;;
esac
	echo "安装zabbix、mysql、apache、php等相关组件"
        yum -y install zabbix-server-mysql zabbix-web-mysql zabbix-agent mariadb mariadb-devel mariadb-server  net-tools yum-utils

	sleep 3
	systemctl start mariadb.service
	mysqladmin  -uroot password "$passwod"

	echo "创建zabbix数据库，和用户名密码"
	echo "create database zabbix character set utf8 collate utf8_bin;" | mysql -uroot -p"$passwod"
#	identified by 'zabbix'为zabbix密码
	echo "grant all privileges on zabbix.* to zabbix@'localhost' identified by 'zabbix';" | mysql -uroot -p"$passwod"
	echo "flush privileges;" | mysql -uroot -p"$passwod"


echo "导入数据库"
zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -pzabbix zabbix

echo "修改zabbix 配置文件"
sed -i '/# DBPassword=/a\DBPassword=zabbix' /etc/zabbix/zabbix_server.conf
sed -i '/# php_value date.timezone Europe\/Riga/a\ php_value date.timezone PRC' /etc/httpd/conf.d/zabbix.conf

cat > /usr/share/zabbix/conf/zabbix.conf.php <<END
<?php
// Zabbix GUI configuration file.
global $DB, $HISTORY;
\$DB['TYPE']                             = 'MYSQL';
\$DB['SERVER']                   = 'localhost';
\$DB['PORT']                             = '0';
\$DB['DATABASE']                 = 'zabbix';
\$DB['USER']                             = 'zabbix';
\$DB['PASSWORD']                 = 'zabbix';
// Schema name. Used for IBM DB2 and PostgreSQL.
\$DB['SCHEMA']                   = 'zabbix';
\$ZBX_SERVER                             = 'localhost';
\$ZBX_SERVER_PORT                = '10051';
\$ZBX_SERVER_NAME                = '';
\$IMAGE_FORMAT_DEFAULT   = IMAGE_FORMAT_PNG;
// Uncomment this block only if you are using Elasticsearch.
// Elasticsearch url (can be string if same url is used for all types).
//$HISTORY['url']   = [
//              'uint' => 'http://localhost:9200',
//              'text' => 'http://localhost:9200'
//];
// Value types stored in Elasticsearch.
//$HISTORY['types'] = ['uint', 'text'];
END
	
	
echo "启动服务，设置开机启动"
systemctl restart zabbix-server zabbix-agent httpd
systemctl enable zabbix-server zabbix-agent httpd mariadb
echo "密码账户保持在/tmp/zabbix.pa"
echo "数据库默认root密码 : $passwod" >> /tmp/zabbix.pa
echo "zabbix 数据库名称、zabbix连接数据库用户名:zabbix、zabbix连接数据库密码:zabbix" >> /tmp/zabbix.pa
echo "zabbix web 用户名：Admin、密码：zabbix" >> /tmp/zabbix.pa
echo "打开http://$ip/zabbix，进行下一步安装" >> /tmp/zabbix.pa
